### ISSUE TITLE
split subcommand

### ISSUE THREAD

**Issue by tkawachi** [tkawachi/aichat#14]

**Comment by tkawachi** [comment]
案1: `--split` をつける

```
aichat --split command1
```

入力できるサイズに切り分けて、それぞれ prompt に入力し、出力を出す。

案2: split は別コマンド

```
cat foo.txt | aichat split | xargs -0 aichat command1
```

標準入力からしか読めないと使い勝手悪そう。

**Comment by tkawachi** [comment]
fold もできるようにしたい

**Comment by tkawachi** [comment]
fold なので、最初の part 用の prompt と、2つ目以降の part 用の prompt を分けて設定したい。

例えばこんな感じ？

```
first:
  messages:
    - role: system
      content: aaaa
    - role: user
      content: $INPUT
subsequent:
  messages:
    - role: system
      content: aaaa $OUTPUT
    - role: user
      content:  $INPUT
```

`$OUTPUT` には前のpartを処理した出力が入る。
